# Lab Test




## 0. Prerequisite

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

## 문제 1
---

2 x 2 행렬을 나타내는 constant 를 정의하시오. 

단, 값은 1, 2, 3, 4 이며 타입은 float32 으로 하시오. 

* **출력형식**

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=array([[1., 2.],[3., 4.]], dtype=float32)>

---

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

## 문제 2
---
np.array[[1,2,3],[4,5,6]] 을 Variable 로 정의하시오.

* **출력형식**


<tf.Variable 'Variable:0' shape=(2, 3) dtype=int64, numpy=array([[1, 2, 3],[4, 5, 6]])>

---

In [14]:
arr = np.array([[1,2,3],[4,5,6]])
tf.Variable(arr)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

## 문제 3
---
주어진 tensor 에서 특정 elements 를 추출하시오.

* **주어진 tensor**

```python
t1 = tf.constant([0, 1, 2, 3, 4, 5, 6, 7])

t2 = tf.constant([[0, 1, 2, 3, 4],
                  [5, 6, 7, 8, 9],
                  [10, 11, 12, 13, 14],
                  [15, 16, 17, 18, 19]])

t3 = tf.constant([[[1, 3, 5, 7],
                   [9, 11, 13, 15]],
                  [[17, 19, 21, 23],
                   [25, 27, 29, 31]]
                  ])
```

* **출력형식**

t1 tf.Tensor([1 2 3], shape=(3,), dtype=int32)

t2 tf.Tensor( [[ 1 2] [ 6 7] [11 12]], shape=(3, 2), dtype=int32)

t3 tf.Tensor([[[25 27]]], shape=(1, 1, 2), dtype=int32)

---

## 문제 4
---
shape 이 3 x 16 x 16 인 tensor를 생성하시오.

단, 값은 모두 1로 설정하시오.

* **출력형식**


<tf.Tensor: shape=(3, 16, 16), dtype=float32, numpy=생략>

---

## 문제 5
---
shape 이 3 x 16 x 16 인 tensor를 3개 생성하시오.

* 첫 번째 tensor는 값이 모두 0 
* 두 번째 tensor는 값이 모두 1
* 세 번째 tensor는 값이 모두 2

단, 3개의 tensors를 하나의 tensor 에 저장하시오.

* **출력형식**

<tf.Tensor: shape=(3, 3, 16, 16), dtype=float32, numpy=생략>

## 문제 6
---
shape 이 3 x 16 x 16 인 tensor (dtype=int32) 를 8개 생성하시오.

* tensor의 값은 0~255 범위의 random 정수값

단, 8개의 tensors를 하나의 tensor 에 저장하시오.

* **출력형식**

<tf.Tensor: shape=(8, 3, 16, 16), dtype=int32, numpy=생략>

## 문제 7
---
shape 이 3 x 16 x 16 인 tensor (dtype=flaot32) 를 8개 생성하시오.

* tensor의 값은 -1~1 범위의 random 실수값

단, 8개의 tensors를 하나의 tensor 에 저장하시오.

* **출력형식**

<tf.Tensor: shape=(8, 3, 16, 16), dtype=int32, numpy=생략>

## 문제 8
---
주어진 MPG dataset을 이용하여 데이터를 분석하시오.

* 결측값을 찾아 해당 컬럼의 평균값으로 대체
* MPG, Cylinders, Horsepower, Weight 컬럼들의 합, 평균, 최솟값, 최댓값
* Horsepower 가 가장 큰 데이터의 row 번호 (0부터 시작)
* Horsepower 가 가장 큰 데이터 (하나임)

```python
#pip install -q seaborn
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
#import seaborn as sns

# Make NumPy printouts easier to read.
np.set_printoptions(precision=3, suppress=True)
import tensorflow as tf

url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
column_names = ['MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight',
                'Acceleration', 'Model Year', 'Origin']

raw_dataset = pd.read_csv(url, names=column_names,
                          na_values='?', comment='\t',
                          sep=' ', skipinitialspace=True)
raw_dataset.head()
# 결측값 처리
dataset = tf.Variable(raw_dataset)

```

## 문제 9
---
주어진 이미지를 이용하여 다음 값을 계산하시오.

* 각 채널(RGB) 별 이미지의 평균값 (3개)
* 각 채널(RGB)을 평균값으로 병합 (이미지 한개)

```python
import tensorflow as tf

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()
print(x_train.shape)
print(x_train[0,].shape)
image = x_train[3,]

fig, ax = plt.subplots(figsize=(5,5))
ax.imshow(image)

```

# 과제 1

주어진 Auto MPG dataset 데이터 셋을 이용하여 자동차의 연비를 예측하는 모델을 구현하시오.


**제출**

구현한 코드가 담긴 colab 파일을 PLATO "텐서플로 과제 제출 게시판"에 제출하세요. (4/23까지)

**참고**

https://www.tensorflow.org/tutorials/keras/regression


```python
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
column_names = ['MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight',
                'Acceleration', 'Model Year', 'Origin']

raw_dataset = pd.read_csv(url, names=column_names,
                          na_values='?', comment='\t',
                          sep=' ', skipinitialspace=True)
```